<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks Condition="'$(BuildLib)' == 'true'">net9.0</TargetFrameworks>
    <TargetFrameworks Condition="'$(BuildLib)' != 'true'">net9.0-windows10.0.19041</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <RootNamespace>ThermalPrint</RootNamespace>
    <AssemblyName>ThermalPrint</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(BuildLib)' != 'true'">
    <OutputType>WinExe</OutputType>
    <DefineConstants>$(DefineConstants);GUI</DefineConstants>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(BuildLib)' == 'true'">
    <OutputType>Library</OutputType>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Plugin.BLE" Version="3.2.1" />
  </ItemGroup>
  <ItemGroup Condition="'$(BuildLib)' != 'true'">
    <None Include="thermalprint.png" CopyToOutputDirectory="PreserveNewest" />
    <PackageReference Include="Avalonia" Version="11.2.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.3" />
    <PackageReference Include="Avalonia.Themes.Simple" Version="11.2.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.3" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.3" />
    <PackageReference Include="SkiaSharp" Version="3.116.1" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
  </ItemGroup>
</Project>
